"""Sentence-aware expressive translation orchestration.

This layer composes the existing translation's local tone analysis, sentence
emoji decoration and the local visual asset library.  It never calls an AI or
external image service and any failure falls back to the unmodified translation.
"""
from __future__ import annotations

import re
from dataclasses import dataclass

import expressive_assets
import translation_extras

EXPRESSIVE_ENGINE_VERSION = "2026-07-14.2-text-first-visual-card"


@dataclass(frozen=True)
class ExpressiveSettings:
    enabled: bool = True
    display_mode: str = "smart"
    intensity: str = "natural"
    visual_style: str = "auto"
    emoji_enabled: bool = True
    images_enabled: bool = True
    short_message_image_enabled: bool = True
    short_message_max_chars: int = 80
    formal_safety_enabled: bool = True
    ocr_enabled: bool = True


@dataclass(frozen=True)
class ExpressiveResult:
    text: str
    tone: str = "neutral"
    visual_mood: str = ""
    decorated_count: int = 0
    visual: expressive_assets.VisualSelection | None = None


_MODE_ALIASES = {"visual": "image", "balanced": "natural"}
_VALID_MODES = {"off", "tone_only", "emoji", "image", "card", "smart"}
_VALID_INTENSITY = {"subtle", "natural", "lively"}


def normalise_mode(value: str | None) -> str:
    token = str(value or "smart").strip().lower()
    token = _MODE_ALIASES.get(token, token)
    return token if token in _VALID_MODES else "smart"


def normalise_intensity(value: str | None) -> str:
    token = str(value or "natural").strip().lower()
    token = _MODE_ALIASES.get(token, token)
    return token if token in _VALID_INTENSITY else "natural"


def normalise_max_chars(value: object, default: int = 80) -> int:
    try:
        parsed = int(value)
    except (TypeError, ValueError):
        parsed = default
    return max(20, min(parsed, 500))


def compact_length(text: str | None) -> int:
    return len(re.sub(r"\s+", "", str(text or "")))


def _should_offer_visual(source: str, settings: ExpressiveSettings, tone: str, context: str) -> tuple[bool, bool]:
    mode = normalise_mode(settings.display_mode)
    if not settings.images_enabled or mode not in {"image", "card", "smart"}:
        return False, False
    length = compact_length(source)
    is_short = length <= normalise_max_chars(settings.short_message_max_chars)
    if is_short and settings.short_message_image_enabled:
        return True, True
    # Long work notices/safety messages can use one restrained formal/factory card.
    if context in {"factory", "workplace"} and length <= 1200 and tone in {
        "announcement", "instruction", "urgent_warning", "management_pressure",
        "crowd_report", "request", "neutral",
    }:
        return True, False
    return False, False


def enhance_translation(
    source_text: str | None,
    translated_text: str | None,
    *,
    source_language: str | None = None,
    context_id: str = "global",
    settings: ExpressiveSettings | None = None,
    from_image_ocr: bool = False,
) -> ExpressiveResult:
    """Return expressive text and an optional local visual selection.

    Translation wording has already been generated by the main API call.  This
    function only decorates and selects local media; exceptions are intentionally
    contained by callers so a valid translation is never blocked.
    """
    cfg = settings or ExpressiveSettings()
    source = str(source_text or "")
    translated = str(translated_text or "")
    mode = normalise_mode(cfg.display_mode)
    intensity = normalise_intensity(cfg.intensity)
    analysis = translation_extras.analyze_message_tone(source, source_language)
    base = ExpressiveResult(translated, analysis.primary, analysis.visual_mood, 0, None)
    if not cfg.enabled or mode == "off" or not translated.strip():
        return base
    if from_image_ocr and not cfg.ocr_enabled:
        return base

    context = expressive_assets.classify_context(source)
    effective_intensity = intensity
    # Dense factory data should remain precise. Ordinary workplace prose still
    # receives sentence-level semantic emoji under natural/lively modes.
    if cfg.formal_safety_enabled and context == "factory" and re.search(
        r"\d+(?:\.\d+)?\s*(?:kg|g|t|mm|cm|m|%|°c|℃)|工單|料號|爐號",
        source,
        re.I,
    ):
        effective_intensity = "subtle"

    decorated_text = translated
    decorated_count = 0
    visual_mood = analysis.visual_mood
    dominant_tone = analysis.primary
    allow_inline_emoji = cfg.emoji_enabled and mode in {"emoji", "smart"}
    # A terse factory-process question (for example asking what is wrong with
    # spray painting) is operational data, not casual chat.  Under the formal
    # safety policy, preserve exact copyable output instead of appending 🤔.
    if cfg.formal_safety_enabled and context == "factory" and analysis.primary in {"question", "request"}:
        if re.search(
            r"噴漆|研磨|冷抽|退火|酸洗|矯直|拋光|倒角|工單|料號|機台|設備|"
            r"\b(?:painting|grinding|annealing|pickling|polishing|work\s*order|machine|equipment)\b",
            source,
            re.I,
        ):
            allow_inline_emoji = False
    if allow_inline_emoji:
        plan = translation_extras.build_expression_plan(
            source,
            translated,
            analysis=analysis,
            source_language=source_language,
            enabled=True,
            mode="emoji",
            intensity=effective_intensity,
        )
        decorated_text = plan.text
        decorated_count = plan.decorated_count
        visual_mood = plan.visual_mood
        dominant_tone = plan.dominant_tone

    visual = None
    allow_visual, is_short = _should_offer_visual(source, cfg, dominant_tone, context)
    if allow_visual:
        # Smart mode never emits a bare standalone image.  A Flex card with a
        # translated-text preview makes it explicit that the visual is secondary
        # decoration.  Bare ImageMessage remains available only when an operator
        # deliberately chooses the backend `image` mode.
        presentation = "image" if mode == "image" else "card"
        visual = expressive_assets.select_visual(
            source_text=source,
            tone=dominant_tone,
            visual_mood=visual_mood,
            preferred_style=cfg.visual_style,
            intensity=effective_intensity,
            presentation=presentation,
            context_id=context_id,
            short_message=is_short,
            formal_safety=cfg.formal_safety_enabled,
        )

    return ExpressiveResult(
        text=decorated_text,
        tone=dominant_tone,
        visual_mood=visual_mood,
        decorated_count=decorated_count,
        visual=visual,
    )
