const assert=require('node:assert/strict');
const {JSDOM,VirtualConsole}=require(process.env.JSDOM_PATH||'jsdom');
const base=process.env.FACTORY_UI_URL||'http://127.0.0.1:8765';
console.log('CHECK factory pages: ci96-page-lifecycle');
const windows=new Set();
async function until(fn,label){for(let i=0;i<100;i++){if(fn())return;await new Promise(r=>setTimeout(r,25));}throw new Error('Timeout: '+label);}
async function adminReady(page,label){await until(()=>page.d.querySelector('#factory-admin-root')?.getAttribute('aria-busy')==='false',label);assert(!page.d.querySelector('#fa-notice').classList.contains('factory-error'),page.d.querySelector('#fa-notice').textContent);}
function close(w){if(w.document)w.dispatchEvent(new w.Event('pagehide'));w.close();windows.delete(w);}
async function open(path,savedGroup){const vc=new VirtualConsole();const errors=[];vc.on('jsdomError',e=>{errors.push(e.message);console.error('DOM error',e.message)});const dom=await JSDOM.fromURL(base+path,{runScripts:'dangerously',resources:'usable',virtualConsole:vc,beforeParse(w){windows.add(w);if(savedGroup)w.localStorage.setItem('factory-selected-group-v1',savedGroup);w.factoryRequests=[];w.AbortController=AbortController;w.AbortSignal=AbortSignal;w.fetch=(url,options)=>{w.factoryRequests.push(String(url));return fetch(new URL(url,w.location.href),options);};w.HTMLElement.prototype.scrollIntoView=()=>{};w.URL.createObjectURL=()=> 'blob:test-qr';w.URL.revokeObjectURL=()=>{};w.navigator.clipboard={writeText:async text=>{w.lastCopied=text}};w.alert=text=>{w.lastAlert=text};}});return {dom,w:dom.window,d:dom.window.document,errors};}
(async()=>{
 const admin=await open('/preview-admin');const {w,d}=admin;await adminReady(admin,'admin fully loaded').catch(e=>{console.log(d.body.textContent.slice(0,1500));throw e});
 assert(d.querySelector('#fa-health').textContent.includes('訊息編輯'));
 const initialVersion=JSON.parse(await (await fetch(base+'/api/admin/factory')).text()).settings_version;
 assert.equal(d.querySelector('#fa-ack-reminder').checked,false);assert.equal(d.querySelector('#fa-ack-minutes').value,'30');assert.equal(d.querySelector('#fa-ack-repeat').checked,true);
 d.querySelector('#fa-ack-reminder').checked=true;d.querySelector('#fa-ack-minutes').value='15';
 d.querySelector('#fa-mode').value='mentioned';d.querySelector('#fa-save-options').click();await until(()=>d.querySelector('#fa-notice').textContent.includes('設定已儲存'),'mode and reminder save');
 let saved=await (await fetch(base+'/api/admin/factory')).json();assert.equal(saved.settings.groups[Object.keys(saved.settings.groups)[0]].translation_mode,'mentioned');assert.notEqual(saved.settings_version,initialVersion);
 assert.deepEqual(saved.ack_settings.groups[d.querySelector('#fa-group').value],{ack_reminder_enabled:true,ack_reminder_minutes:15,ack_reminder_repeat:true});
 for(const [id,value] of [['code','TEST9'],['name-zh','測試站'],['name-id','Stasiun uji'],['context','PMI 檢驗流程'],['sop-zh','先確認鋼種'],['sop-id','Pastikan jenis baja']]) d.querySelector('#fa-'+id).value=value;
 d.querySelector('#fa-save-station').click();await until(()=>d.querySelector('#fa-notice').textContent.includes('設備資料已儲存'),'station save');assert(d.querySelector('#fa-station-list').textContent.includes('TEST9'));
 const tr=[...d.querySelectorAll('#fa-station-list tr')].find(e=>e.textContent.includes('TEST9'));[...tr.querySelectorAll('button')].find(e=>e.textContent==='QR Code').click();await until(()=>d.querySelector('#fa-qr-preview img'),'QR preview');assert(d.querySelector('#fa-qr-preview a').download.includes('TEST9'));
 d.querySelector('#fa-load-receipts').click();await until(()=>d.querySelector('#fa-receipts').textContent.includes('PMI'),'receipt load');assert(d.querySelector('#fa-receipts').textContent.includes('未回覆'));
 const firstGroup=d.querySelector('#fa-group').value,secondGroup=[...d.querySelector('#fa-group').options].find(o=>o.value!==firstGroup).value;
 d.querySelector('#fa-receipt-group').value=secondGroup;d.querySelector('#fa-receipt-group').dispatchEvent(new w.Event('change'));
 await until(()=>d.querySelector('#fa-receipts').textContent.includes('B 班'),'other group result');assert.equal(d.querySelector('#fa-group').value,secondGroup);assert(d.querySelector('#fa-receipt-scope').textContent.includes('B 班'));
 assert.equal(d.querySelector('#fa-ack-reminder').checked,false);assert.equal(d.querySelector('#fa-ack-minutes').value,'30');assert.equal(d.querySelector('#fa-ack-repeat').checked,true);
 assert.equal(w.localStorage.getItem('factory-selected-group-v1'),secondGroup);
 const reopened=await open('/preview-admin',w.localStorage.getItem('factory-selected-group-v1'));
 await adminReady(reopened,'remembered group fully loaded');assert(reopened.d.querySelector('#fa-receipts').textContent.includes('B 班'));assert.equal(reopened.d.querySelector('#fa-group').value,secondGroup);assert.deepEqual(reopened.errors,[]);close(reopened.w);
 d.querySelector('#fa-receipt-group').value=firstGroup;d.querySelector('#fa-receipt-group').dispatchEvent(new w.Event('change'));await until(()=>d.querySelector('#fa-receipts').textContent.includes('PMI'),'return to first group');
 assert.equal(d.querySelector('#fa-ack-reminder').checked,true);assert.equal(d.querySelector('#fa-ack-minutes').value,'15');
 const reply=await (await fetch(base+'/preview-receipt-reply',{method:'POST',headers:{'Content-Type':'application/json'},body:'{}'})).json();
 assert.equal(reply.feedback,'');assert.equal(reply.emitted_count,0);
 for(const timestamp of [500,550,580]){
  const duplicate=await (await fetch(base+'/preview-receipt-reply',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({timestamp})})).json();
  assert.equal(duplicate.emitted_count,0);assert.equal(duplicate.feedback,'');
 }
 d.querySelector('#fa-load-receipts').click();await until(()=>d.querySelector('#fa-receipts').textContent.includes('✅ 已了解：Adi'),'actual acknowledgement in admin');
 assert(d.querySelector('#fa-receipt-status').textContent.includes('A 班'));assert(d.querySelector('#fa-receipts').textContent.includes('發起人：管理者'));
 await fetch(base+'/preview-receipt-reply',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({action:'factory_help',timestamp:600})});
 Object.defineProperty(d,'visibilityState',{configurable:true,value:'visible'});d.querySelector('#fa-receipts-section').getBoundingClientRect=()=>({height:500,top:0,bottom:500});
 const originalNow=w.Date.now;w.Date.now=()=>originalNow()+21000;w.dispatchEvent(new w.Event('focus'));await until(()=>d.querySelector('#fa-receipts').textContent.includes('❓ 需要說明：Adi'),'visible receipt auto refresh');
 Object.defineProperty(d,'visibilityState',{configurable:true,value:'hidden'});const requests=w.factoryRequests.length;w.Date.now=()=>originalNow()+45000;w.dispatchEvent(new w.Event('focus'));await new Promise(r=>setTimeout(r,30));assert.equal(w.factoryRequests.length,requests);w.Date.now=originalNow;
 console.log('PASS receipts: silent first/repeated taps and redelivery, stored response, correct group, visible refresh, hidden pause');
 d.querySelector('#fa-menu').value='richmenu-'+'a'.repeat(32);d.querySelector('#fa-insight-mode').value='daily';d.querySelector('#fa-load-insight').click();await until(()=>d.querySelector('#fa-insight-result').textContent.includes('20260906'),'daily insight');assert(d.querySelector('#fa-insight-result').textContent.includes('42'));
 console.log('PASS admin: mode and per-group reminder persistence, equipment/SOP save, QR preview, receipt list');
 const member=await open('/preview-factory');await until(()=>member.d.querySelector('#factory-group').textContent.includes('A 班'),'member loaded');
 member.d.querySelector('#factory-code').value='TEST9';member.d.querySelector('#factory-lookup button').click();await until(()=>member.d.querySelector('#factory-station-name').textContent.includes('TEST9'),'station lookup');assert.equal(member.d.querySelector('#factory-sop-zh').textContent,'先確認鋼種');
 member.d.querySelector('#factory-input').value='檢驗一下';member.d.querySelector('#factory-translate').click();await until(()=>member.d.querySelector('#factory-message').textContent.includes('翻譯完成'),'station translation');assert(member.d.querySelector('#factory-station-output').textContent.includes('檢驗一下'));
 member.d.querySelector('#factory-copy').click();await until(()=>member.w.lastCopied,'copy');assert(member.w.lastCopied.includes('Pemeriksaan PMI'));
 member.d.querySelector('#factory-share').click();await until(()=>member.d.querySelector('#factory-message').textContent.includes('已分享'),'share success');
 member.w.liff.shareTargetPicker=async()=>undefined;member.d.querySelector('#factory-share').click();await until(()=>member.d.querySelector('#factory-message').textContent.includes('已取消'),'share cancel');
 member.d.querySelector('#factory-scan').click();await until(()=>member.d.querySelector('#factory-station-name').textContent.startsWith('PMI'),'scan lookup');
 member.w.liff.scanCodeV2=async()=>{throw new Error('相機權限未開啟')};member.d.querySelector('#factory-scan').click();await until(()=>member.d.querySelector('#factory-message').textContent.includes('相機'),'scan failure');assert(!member.d.querySelector('#factory-scan').disabled);
 console.log('PASS member: manual/QR lookup, bilingual SOP, translation, full copy, share success/cancel, camera failure');
 const form=await open('/liff/settings?view=form&id=f1');await until(()=>form.d.querySelector('#field-pmi'),'form loaded');
 form.d.querySelector('button[type=submit]').click();assert(!form.d.querySelector('#verifiedForm').checkValidity());
 form.d.querySelector('#field-pmi').checked=true;form.d.querySelector('#field-quantity').value='3.5';form.d.querySelector('button[type=submit]').click();await until(()=>form.d.body.textContent.includes('提交成功'),'verified form submit');close(form.w);
 const duplicate=await open('/liff/settings?view=form&id=f1');await until(()=>duplicate.d.body.textContent.includes('已填寫'),'duplicate form');close(duplicate.w);
 console.log('PASS form: LIFF entry, required fields, numeric input, submit, duplicate display');
 const reminder=await (await fetch(base+'/preview-ack-reminder',{method:'POST'})).json();
 assert.equal(reminder.state,'sent',JSON.stringify(reminder));assert.equal(reminder.messages[0].type,'textV2');
 assert.deepEqual(Object.values(reminder.messages[0].substitution).map(item=>item.mentionee),[{type:'user',userId:'U'+'b'.repeat(32)}]);
 assert(!reminder.messages[0].text.includes('提醒全體'));
 assert(JSON.stringify(reminder.messages[1]).includes('了解/Paham (0)'));
 assert(JSON.stringify(reminder.messages[1]).includes('已知成員未回覆/Belum menjawab (1): Adi'));
 d.querySelector('#fa-load-receipts').click();
 await until(()=>d.querySelector('#fa-receipts').textContent.includes('已完成個別 @ 提醒'),'actual individual mention status');
 assert(d.querySelector('#fa-group-section').textContent.includes('名單不完整也不改用 @All'));
 assert(d.querySelector('#fa-receipts').textContent.includes('另有 1 人尚未取得身分'));
 assert(d.querySelector('#fa-receipts').textContent.includes('已知成員未回覆為 0 即自動停止提醒'));
 const completing=await (await fetch(base+'/preview-ack-reminder',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({repeat:true})})).json();
 assert.equal(completing.state,'repeat_pending');
 const completed=await (await fetch(base+'/preview-receipt-reply',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({token:completing.token,timestamp:800})})).json();
 assert.equal(completed.feedback,'');assert.equal(completed.emitted_count,0);
 d.querySelector('#fa-load-receipts').click();
 await until(()=>d.querySelector('[data-token="'+completing.token+'"]')?.textContent.includes('已知成員未回覆為 0，已自動停止提醒'),'zero pending auto stop status');
 assert(!d.querySelector('[data-stop-token="'+completing.token+'"]'));
 const finished=(await (await fetch(base+'/api/admin/factory/receipts?group_id='+firstGroup)).json()).notices.find(row=>row.token===completing.token);
 assert.equal(finished.wake_at,null);assert.equal(finished.next_reminder_at,null);assert.equal(finished.reminder_state,'no_pending');
 const repeating=await (await fetch(base+'/preview-ack-reminder',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({repeat:true})})).json();
 assert.equal(repeating.state,'repeat_pending');
 d.querySelector('#fa-load-receipts').click();
 await until(()=>d.querySelector('[data-stop-token="'+repeating.token+'"]'),'per-notice stop control');
 d.querySelector('[data-stop-token="'+repeating.token+'"]').click();
 await until(()=>d.querySelector('#fa-notice').textContent.includes('已停止這筆通知'),'stop reminder feedback');
 assert(d.querySelector('[data-token="'+repeating.token+'"]').textContent.includes('此通知已手動停止提醒'));
 assert(!d.querySelector('[data-stop-token="'+repeating.token+'"]'));
 const late=await (await fetch(base+'/preview-receipt-reply',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({token:repeating.token,timestamp:900})})).json();
 assert.equal(late.feedback,'');assert.equal(late.emitted_count,0);
 const stopped=(await (await fetch(base+'/api/admin/factory/receipts?group_id='+firstGroup)).json()).notices.find(row=>row.token===repeating.token);
 assert.equal(stopped.responses['U'+'b'.repeat(32)].status,'understood');
 assert.equal(stopped.reminder_state,'stopped');assert.equal(stopped.wake_at,null);assert.equal(stopped.next_reminder_at,null);
 assert(d.querySelector('#fa-members').textContent.includes('Adi'));
 d.querySelector('#fa-ack-reminder').checked=false;d.querySelector('#fa-save-options').click();
 await until(()=>d.querySelector('#fa-notice').textContent.includes('群組設定已儲存'),'group reminders off');
 const disabled=await (await fetch(base+'/api/admin/factory')).json();assert.equal(disabled.ack_settings.groups[firstGroup].ack_reminder_enabled,false);
 console.log('PASS reminders: scheduled receipt summary and native pending mentions, zero pending auto stop, late answer stays silent/stopped, group off');
 assert.deepEqual(admin.errors,[]);assert.deepEqual(member.errors,[]);
 close(admin.w);close(member.w);
})().catch(e=>{console.error(e);process.exitCode=1;}).finally(()=>{for(const w of windows)close(w);});
